### ISSUE TITLE
Expose HTTP Context in ValidateConnectionAsync

### ISSUE THREAD

**Issue by SystemDisc** [dotnet/MQTTnet#1125]
### Describe the feature request
I'm am trying to access the HTTP context in `ValidateConnectionAsync` but `MqttConnectionValidatorContext` does not expose it. It would be useful to have the HTTP context to check headers and validate the connection based on those headers.

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
`MqttConnectionValidatorContext` could expose `HttpContext` like so:
```C#
HttpContext HttpContext => _clientAdapter.Connection.GetHttpContext();
```

### Describe alternatives you've considered
I have considered using reflection to access the private member `_clientAdapter`, but it just feels wrong.
```C#
var clientAdapter = (MqttConnectionContext) typeof(MqttConnectionValidatorContext).GetField("_clientAdapter", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(context);
```

### Additional context
N/A

**Comment by metint** [comment]
I would be highly interested in such a feature.

Currently I run an MQTTnet Server using websockets as the communication protocol and I use client certificates for authentication. I further validate client id by comparing it to the subject field in the certificate. When clients directly connect to the broker I get the client certificate in `MqttConnectionValidatorContext.ClientCertificate` and everything is perfect.

The problem is, when the server runs behind a reverse proxy (e.g. nginx), the client certificate cannot reach to the server but can be forwarded in the http header (see [this answer](https://serverfault.com/a/1079377) in ServerFault). Then this information can be accessed via `HttpContext.Request.Headers` and used to create `X509Certificate2` instance.

**Comment by chkr1011** [comment]
The client adapter is now officially exposed in the event arguments for version 4.1.x.
