### ISSUE TITLE
WithMultiThreadedApplicationMessageInterceptor always performs publish

### ISSUE THREAD

**Issue by mazorvanunu** [dotnet/MQTTnet#1350]
### Which project is your bug related to? 
- Server 

### To Reproduce
1. Using this version of MQTTnet 'latest'.
2. Run this code 'WithMultiThreadedApplicationMessageInterceptor(v => v.AllowPublish = false)'.
3. With these arguments '....'.
4. The broker always publish the call

### Expected behavior
broker should not publish the message if specified
note: WithApplicationMessageInterceptor - this works as expected

### Screenshots
see added png please
![mqtt_broker_still_publish_call](https://user-images.githubusercontent.com/19983289/153279138-62d02122-65d2-4e42-a9f3-3c8145d8fa33.png)

**Comment by chkr1011** [comment]
I don' think that this will work because the multi threaded interceptor will just start a new task for every message. So the server will continue with the unaltered event arguments and thus ignore everything. If you want to change the behavior of the server you must use the other interceptor. But you can start a new task on your own including your custom code which can run on another task.

**Comment by chkr1011** [comment]
Closing because I assume that the question is answered.
