### ISSUE TITLE
Project build errors

### ISSUE THREAD

**Issue by friesendrywall** [dotnet/MQTTnet#1362]
Using Visual Studio Community 2019 the project build errors out, perhaps due to not checking every possibility on my initial install, Its not clear.  Could there be another readme or addition with the prerequisites for successfully building this project?

In my case, I just want the standard windows build so I can test with this.

![Screenshot 2022-03-08 09 29 55](https://user-images.githubusercontent.com/5509710/157258224-3a54e628-0203-4b42-8e63-e6529901dc75.png)
.

**Comment by SeppPenner** [comment]
Two problems I can find from reading the error messages:

1. Visual Studio 2019 doesn't support Net6.0 builds, you need to switch to VS2022.
2. If you don't have installed Net6.0, you need to install it, since the projects have dependencies to the framework.

The only other option is to remove all `net6.0` frameworks from the *csproj files (Located under `TargetFrameworks` in the project (In your local folder) and try again.

**Comment by chkr1011** [comment]
Another dependency is the Windows SDK for UWP builds. The project requires the SDK 10.0.18362.0 to be installed. This can be installed via the Visual Studio Installer (Individual Components).

**Comment by friesendrywall** [comment]
Thank you for that clarification.  For now I just ended up using the 3.1.2 standard nuget package.  But it would be nice to include this basic build requirement info somewhere in the repo.

**Comment by SeppPenner** [comment]
> Another dependency is the Windows SDK for UWP builds. The project requires the SDK 10.0.18362.0 to be installed. This can be installed via the Visual Studio Installer (Individual Components).

Er, the readme states 10.0.10240+ as supported UWP version. This doesn't seem to fit...

I've added a small pull request, just let me know if the UWP version needs to be changed :)

**Comment by SeppPenner** [comment]
I have added this to the wiki now: https://github.com/dotnet/MQTTnet/wiki/Build.
