### ISSUE TITLE
Help with TLS - please!

### ISSUE THREAD

**Issue by darl1234567890** [dotnet/MQTTnet#1369]
Hi all,

I've written a c# vs 2022 desktop app which reads a temperature sensor via Modbus.

I've included an mqtt interface using mqttnet such that the app can publish the temperature readings to a mqtt broker via raw tcp.

All working, but I want to employ tls to make the connection secure.
Problem is I have absolutely no experience with tls & I'm finding it very confusing.
Other users will use this software therefore I need to offer those users the same security options (e.g. tls) - but how do I go about doing this?
Do I need to include the tls or can I leave it to the users to implement themselves?

Your help would be very much appreciated because I'm banging my head against the wall with this.
It seems extremely complicated & there appears to be so many options.

Thank you!

Regards,
Darren

**Comment by chkr1011** [comment]
In my opinion this the wrong place for general TLS questions. We also just rely on .net sockets where only a couple of TLS options is available and must be properly set. Server is little bit more complicated but this is also a general topic and not related to this library. Unfortunately I have no other source I can paste here with instructions. Maybe someone else is able to do so.

**Comment by logicaloud** [comment]
After you have build your MQTT client `options` for the TCP connection with the `MqttClientOptionsBuilder`, try something along the following lines:

```
if (mqttClientShouldUseTls)
{
    var p = new MQTTnet.Client.MqttClientOptionsBuilderTlsParameters();
    p.UseTls = true;
    if (mqttClientShouldUseClientCertificate)
    {
        p.Certificates = new List<System.Security.Cryptography.X509Certificates.X509Certificate2>() { ... your certificates ... };
    }
    if (mqttClientShouldAcceptAnyCertificate)
    {
        p.AllowUntrustedCertificates = true;
        p.CertificateValidationHandler = (certContext) => { return true; };
    }
    options = options.WithTls(p);
}
```

This is based on the current master branch (I don't know if there is a difference in v 3.x). 

If the broker expects the client to present a client certificate then you would need to create or issue your own certificates and it may get a little bit more complicated.

**Comment by dazzalogan** [comment]
@logicaloud 

Thank you for your reply.

Unfortunately I'm a complete newbie when it comes to TLS and the implementation thereof, so I'm already lost with your code.
I understand C# well enough, just not the TLS stuff.
What's the list of certificates? And what's an "untrusted" certificate?

The cloud-based brokers we'll typically recommend are CloudMqtt and HiveMQ.
Both of which support and recommend an SSL connection.

As I say; I want to distribute the Windows app. and offer TLS(SSL?) security to the users.
So I'm looking for a package solution to offer them, or at least offer advice in this respect.

I'm still none the wiser. Sorry. :-(

Darren

**Comment by logicaloud** [comment]
You don't need to worry about the TLS details because that is taken care of by .NET and the options builder in MQTTnet. Also, for a start, disregard the client certificates. After you have built your client options, in the simplest form, try this:
```
    var p = new MQTTnet.Client.MqttClientOptionsBuilderTlsParameters();
    p.UseTls = true;
    p.AllowUntrustedCertificates = true;
    p.CertificateValidationHandler = (certContext) => { return true; };
    options = options.WithTls(p);
```
before you build the options for the client connection (that you already do for the TCP connection):

```
mqttClientOptions = options.Build();
```

This should get you connected via TLS but its not good enough for production because all certificates are trusted.  Can you connect via TLS after adding the above to your code? If not, then an example of how you build your MQTT client would help.

After that, you can remove the `AllowUntrustedCertificates` and `CertificateValidationHandler` lines and leave it to .NET and the operating system to determine whether a broker certificate should be trusted.

At some point you'll probably want to read more about TLS, certificates, trust, and so forth, so that you can make informed decisions on how to handle this in production, but this is probably not the forum for it.

**Comment by dazzalogan** [comment]
@logicaloud 

Hi,

Thanks again.

I added your code to my connection function and tried connecting to my (free) CloudMqtt account via the dedicated TLS port, but it does not connect.
Perhaps this is because the port I'm trying to use is closed or not allowed by our IT system?

I think I need to take a step back and understand what I'm actually trying to achieve.
I read of "certificates", but I'm not sure what a "certificate" is in this context.

My connection code below:

`        private async void Connect()
        {
            mqFactory = new MqttFactory();
            mqClient = (MqttClient)mqFactory.CreateMqttClient();
            MqttClientOptions options;

            var p = new MQTTnet.Client.Options.MqttClientOptionsBuilderTlsParameters();
            p.UseTls = true;
            p.AllowUntrustedCertificates = true;
            p.CertificateValidationHandler = (certContext) => { return true; };
            //options = options.WithTls(p);

            if (txtUsername.Text != null && txtPassword.Text != null)
            {
                // Create TCP based options using the builder.
                options = (MqttClientOptions)new MqttClientOptionsBuilder()
                    .WithClientId(txtClientID.Text)
                    .WithTcpServer(txtBrokerAddr.Text, Convert.ToInt32(txtPort.Text))
                    .WithCredentials(txtUsername.Text, txtPassword.Text)
                    .WithCleanSession()
                    .WithTls(p)
                    .Build();
            }
            else
            {
                // Create TCP based options using the builder.
                options = (MqttClientOptions)new MqttClientOptionsBuilder()
                    .WithClientId(txtClientID.Text)
                    .WithTcpServer(txtBrokerAddr.Text, Convert.ToInt32(txtPort.Text))
                    .WithCleanSession()
                    .WithTls(p)
                    .Build();
            }

            mqClient.ConnectedHandler = new MqttClientConnectedHandlerDelegate(MqttClientOpened);
            mqClient.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(MqttClientClosed);
            mqClient.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(MqttClientMessageReceived);

            try
            {
                //mqttRes = mqClient.ConnectAsync(options);                
                //await mqttRes;
                await mqClient.ConnectAsync(options);
            }
            catch (Exception Ex)
            {

            }
            //return mqClient.IsConnected;
        }`

**Comment by darl1234567890** [comment]
@logicaloud

Hi there,

I can connect to the HiveMq cloud free account (tls on port 8883) from home but not from work, therefore I assume it's a port issue at work.

So I'm a small step forward in that at least I can connect to the tls brokers.

However, there's still no certificates involved.

I'm reading that there's a broker certificate & client.
I can obtain the HiveMq cloud broker certificate as a pem file, but I have no idea what this is or how to use it for security?
Can I just use this or should I have a certificate both ends?

Where do I obtain a suitable client cert from?
And considering I'm distributing my software, will I need to purchase a new client cert for each new user?

Thanks

Darren

**Comment by logicaloud** [comment]
When you use TLS then at least the broker already has a certificate.

If you also need to use client certificates then it is probably best to follow one of the guides out there, i.e.:  https://www.hivemq.com/blog/mqtt-security-fundamentals-x509-client-certificate-authentication/

**Comment by SeppPenner** [comment]
> I can obtain the HiveMq cloud broker certificate as a pem file, but I have no idea what this is or how to use it for security?
Can I just use this or should I have a certificate both ends?

If you just use the MQTT client with the `WithTls()` builder method, the operating system / .Net will already handle the certificate validation for you. You don't need to do something special here except if you had a so called `self-signed` certificate (Normally only used in development). Public servers like the one from HiveMQ have a validated certificate that the framework handles.

> Where do I obtain a suitable client cert from?
And considering I'm distributing my software, will I need to purchase a new client cert for each new user?

I'm not sure if you even need some. You can just use username and password authentication over TLS. Client certificates only give you the advantage that you don't need to give out credentials, but just store a certificate in the device (or client) that connects to the MQTT server.

As @chkr1011 already stated, this is not a question of the library itself but a more generic question. @logicaloud has pointed to a source (https://www.hivemq.com/blog/mqtt-security-fundamentals-x509-client-certificate-authentication/), and there is the Wiki as well if you want to add client certificates: https://github.com/dotnet/MQTTnet/wiki/Client#certificate-based-authentication.

**Comment by dazzalogan** [comment]
@SeppPenner 

Hi,
Thanks for your reply.

> If you just use the MQTT client with the WithTls() builder method, the operating system / .Net will already handle the certificate validation for you. You don't need to do something special here except if you had a so called self-signed certificate (Normally only used in development). Public servers like the one from HiveMQ have a validated certificate that the framework handles.

My software has a dedicated MQTT connection window, on this Window there's a broker address, port, clientID, username, password, useTLS and MQTT version connection options to enter/choose.
With this, I can successfully connect to the HiveMQ TLS broker.

Are you saying that this connection is secure enough as it is? and is it encrypted?

If so then I'm confused because I **thought** I needed to purchase some kind of client-side certificate, too - and this has been driving me insane trying to understand it.
I also thought I'd have to purchase a new client-side certificate for every customer who uses this software!

If this HiveMQ connection is inherently secure, then it seems I don't need to do anything more other than recommend to the customer to use the HiveMQ broker as I have in my testing.

Thanks again, and apologies for the off-topic questions. I realise this post is more suited elsewhere, but I can't seem to find the answers I'm looking for anywhere.

**Comment by SeppPenner** [comment]
> Are you saying that this connection is secure enough as it is? and is it encrypted?

Yes, it is encrypted.

> If so then I'm confused because I thought I needed to purchase some kind of client-side certificate, too - and this has been driving me insane trying to understand it.

You can use client certificates as authentication method, but you can use username and password as well (There is nothing more secure with the client certificates).

> If so then I'm confused because I thought I needed to purchase some kind of client-side certificate, too - and this has been driving me insane trying to understand it.

Well, for testing purposes, it's ok. Still, the HiveMQ broker is public and the data can be read by anyone (Just the transport is encrypted). So, I wouldn't use this for productive /sensitive data.
