### ISSUE TITLE
uap

### ISSUE THREAD

**Issue by zhfl123** [dotnet/MQTTnet#1379]
### Verification

Before opening a bug make sure that the following conditions are met.

1. Performance issues are also appearing in RELEASE mode of your application.
2. An increased memory consumption or high CPU load also happens when your application runs in RELEASE mode AND logging is DISABLED.
3. Client issues with not received messages, connection drops etc. can be reproduced via another client application like "MQTTnetApp" (https://github.com/chkr1011/MQTTnetApp) or similar.
4. The bug also appears in the VERY LATEST version of this library. There is no support for older version (due to limited resources) but pull requests for older versions are welcome.

### Which component is your bug related to?

- Client
- ManagedClient
- RcpClient
- Server

### To Reproduce
1. Using this version of MQTTnet '...'.
2. Run this code '....'.
3. With these arguments '....'.
4. See error.

### Additional context / logging
Include debugging or logging information here:

```batch
\\ Put your logging output here.
```
### Code example
Please provide full code examples below where possible to make it easier for the developers to check your issues.

**Ideally a Unit Test (which shows the error) is provided so that the behavior can be reproduced easily.**
 
```csharp
\\ Put your code here.
```

**Comment by SeppPenner** [comment]
I'm not sure what this issue should be about? We can help you in the best way if you fill out the issue template...

**Comment by chkr1011** [comment]
I assume this is a mistake because not actual information is provided. I will close this ticket. If this is wrong please reopen the ticket and provide more details.

**Comment by tjmcode** [comment]
Hans,

 

Whatever request went to you was a mistake, I was just browsing your site.

 

Sincerely,

 

Timothy J. McGuire

President-CEO

C:  810.459.7508

E:  ***@***.***> ***@***.***

P:  <https://tjmcode.github.io/> https://tjmcode.github.io

 



  Software Development / Controls Engineering – since 1987

 

  MicroCODE Incorporated

  55 E. Long Lake Rd, #224

  Troy, MI 48085

  O: 248.457.5704

 M: 855.421.1010

 

   <http://www.mcode.com/>    <https://www.facebook.com/MicroCODEInc>    <https://twitter.com/MicroCODEInc>    <http://www.linkedin.com/company/microcode-incorporated>    

 

Confidentiality Note: This message, including any attachments, may contain confidential and/or privileged material or information and is intended solely for use by the individual to whom it is addressed.  Any review, transmission, dissemination or other use, or taking of any action in reliance upon this message by persons or entities other than the intended recipient is prohibited and may be unlawful. If you received this message in error, please notify the sender, do not disclose its contents to others, and delete it from your systems.  Any other use of this message and/or attachments is prohibited.  This message is not meant to constitute an electronic signature or intent to contract electronically.

**Comment by SeppPenner** [comment]
@tjmcode Never mind, I just got confused by the message ;)
