### ISSUE TITLE
Connecting to Hive / certificate question

### ISSUE THREAD

**Issue by PNPTransistor** [dotnet/MQTTnet#1436]
Hi all,

I'm quite new to MQTT therefore apologies in advance if I'm asking a silly question:

I have setup a free Hive account and I'm finding I can connect to it with or without using the Hive certificate.
I "thought" that you "had" to use the server certificate in order to make a connection, so why can I connect with or without it?

What is the point or purpose of the certificate if it's not even required to connect?

Thanks

**Comment by chkr1011** [comment]
Please check the settings of the hive account. We cannot support here because this library has no relations to the Hive MQTT server product. Probably the settings are allowing both connection types and you probably have to disable one? Only guessing. Maybe you should contact the owners of Hive for assistance.
