### ISSUE TITLE
MqttClientOptionsBuilder: Method WithWillMessage() missing

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [dotnet/MQTTnet#1453]
### Describe the feature request
After an update to MQTTnet v4 I noticed that the method `WithWillMessage()` is missing from MqttClientOptionsBuilder.
A lot of methods have been re-added after the initial release of v4, but not this one.

### Which project is your feature request related to?
- Client

### Describe the solution you'd like
An answer whether this decision is intentional and it is required for consumers to adapt to the new API or this is not intentional and can and will be fixed in the future allowing consumers to wait before integration.

### Describe alternatives you've considered
Previous implementation:
````
options.MqttClientOptionsBuilder.WithWillMessage(msg);
````
Alternative implementation with v4 (for me, your results may vary depending on what is important to you):
````
options.MqttClientOptionsBuilder.WithWillTopic(msg.Topic)
    .WithWillPayload(msg.Payload)
    .WithWillRetain(msg.Retain)
    .WithWillPayloadFormatIndicator(msg.PayloadFormatIndicator)
    .WithWillContentType(msg.ContentType);
````

### Additional context
none

**Comment by chkr1011** [comment]
This message was removed in version 4 because the will message is not 100% the same as a regular message. So according to the RFC all fields in the package were converted to corresponding methods in the connection options builder like "WithWillTopic" etc. Properties which are missing there like "ReponseTopic" etc. are not supported in will messages.
