### ISSUE TITLE
Use ReadonlyMemory replace byte Array

### ISSUE THREAD

**Issue by xljiulang** [dotnet/MQTTnet#1577]
Hello, can we change the `byte[]` type of the `Payload` to `ReadonlyMemory<byte>` so that it can be used together with `ArrayPool<byte>` to reduce GC pressure?

eg.
```c#
var message = new GoogleMessage();
var size = message.CalculateSize();
Debug.Assert(960 == size);

var buffer = ArrayPool<byte>.Shared.Rent(size);
Debug.Assert(1024 == buffer.Length);

var output = new CodedOutputStream(buffer);
message.WriteTo(output);
var payload = buffer.AsMemory(0, size);
// mqtt.SendAsync(payloadPacket)

ArrayPool<byte>.Shared.Return(buffer);
```

**Comment by chkr1011** [comment]
I assume that you can already make use of the Array Pool. It returns a simple byte array which can be already used as the payload.

**Comment by xljiulang** [comment]
@chkr1011 
However, the length of the rent `byte[]` is not equal to the length of the valid data(1024 != 960), which cannot be directly used as the payload. Instead, i need to copy the first 960 bytes of the rent `byte[]` as the payload, which is no different from new byte[960].

**Comment by gfoidl** [comment]
> there is no disruption to the user

Strictly speaking this in an API-breaking change (different type).

`ROM<byte>` could be exposed as additional member, e.g. as `PayloadMemory` and the current `Payload` just forwards to `PayloadMemory` internally. In .NET the SocketsAwaitable uses as similar approach.

**Comment by chkr1011** [comment]
We cannot change the type to Memory etc. because we still need to support older frameworks like 4.5.2, UWP etc.

I have a proposal on how to solve this issue. In my opinion the only problem is that there is currently no chance to pass the bounds of the payload so that a larger array from the pool can be reused etc.

So, I will add two new properties. 

**PayloadOffset** is the offset of the payload which will be initialized with **0** which is correct for all cases and causes no breaking changes.

**PayloadLength** is the length which should be used when accessing the payload array. This will be initialized with **int.MaxValue** which indicates (as a magic number) that the value from the payload array should be used by default. This approach is a little bit ugly but will keep the API stable without breaking changes. If the length is set, the value is used. Probably a bounds check can be made so that a higher value than the actual array size of the payload indicates that the full array should be used.

These two new properties will be properly filled for received messages but without any benefit because they will be **0** and the actual length of the payload all the time.

@gfoidl This might be the start of the implementation of a disposable message which allows using an array pool internally. But I would not implement this feature in this ticket.

Any thoughts?

**Comment by gfoidl** [comment]
This reminds me of `ArraySegment<byte>` which has offset and length, avaiable from .NET Fx 2.0 onwards.
Provides all the semantics that are needed.
Of course if the approache with `PayloadLength` and `PayloadOffset` is easier for the implementation, so go with that. As consumer it's easy to get an ROM<byte> from this.

Yep, the pooling-story should be separate and maybe as follow-up step.

**Comment by xljiulang** [comment]
@chkr1011
So far, adding `PayloadOffset` and `PayloadLength` is the most reasonable way to do this. Maybe the new Api could be designed like this:
```c#
 public int PayloadOffset { get; set; } = 0;
 public int? PayloadLength{ get; set; } = null;
```

And then we add `WithPayload(ReadOnlyMemory<byte>)`  in MqttApplicationMessageBuilder:
```c#
#if NETCOREAPP3_1_OR_GREATER 
        public MqttApplicationMessageBuilder WithPayload(ReadOnlyMemory<byte> payload)
        {
            if (MemoryMarshal.TryGetArray(payload, out var segment))
            {
                _payload = segment.Array;
                _payloadOffset = segment.Offset;
                _payloadLength = segment.Count;
            }
            else
            {
                _payload = payload.ToArray();
            }
            return this;
        }
#endif
```

**Comment by xljiulang** [comment]
I tried to design an interface for `IPayloadSegmentable`:
```c#
interface IPayloadSegmentable
{
    /// <summary>
    /// Get or set Payload array
    /// </summary>
    byte[] Payload { get; set; }

    /// <summary>
    /// Get or set the offset of Payload
    /// </summary>
    int PayloadOffset { get; set; }

    /// <summary>
    /// Get or set the effective number of bytes of Payload
    /// Leaving null means equal to the total length of Payload minus PayloadOffset
    /// </summary>
    int? PayloadCount { get; set; }
}
```
Then let the related type implement the interface:
```c#
public sealed class MqttApplicationMessage: IPayloadSegmentable
```
```c#
public sealed class MqttPublishPacket : MqttPacketWithIdentifier, IPayloadSegmentable
```

A internal `PayloadSegmentExtensions` type is provided to facilitate operation of IPayloadSegmentable
```c#
static class PayloadSegmentExtensions
{
    private static readonly ArraySegment<byte> empty = new ArraySegment<byte>(EmptyBuffer.Array);

    public static int? GetPayloadCount(this IPayloadSegmentable segmentable)
    {
        if (segmentable.Payload == null)
        {
            return null;
        }

        return segmentable.PayloadCount == null
            ? segmentable.Payload.Length - segmentable.PayloadOffset
            : segmentable.PayloadCount.Value;
    }

    public static ArraySegment<byte> GetPayloadSegment(this IPayloadSegmentable segmentable)
    {
        if (segmentable.Payload == null)
        {
            return empty;
        }

        var count = segmentable.PayloadCount == null
            ? segmentable.Payload.Length - segmentable.PayloadOffset
            : segmentable.PayloadCount.Value;

        return new ArraySegment<byte>(segmentable.Payload, segmentable.PayloadOffset, count);
    }

#if NETCOREAPP3_1_OR_GREATER || NETSTANDARD2_1
    public static bool SequenceEqual(this ArraySegment<byte> x, ArraySegment<byte> y)
    {
        return x.Count == y.Count && x.AsSpan().SequenceEqual(y.AsSpan());
    }
#else
    public static bool SequenceEqual(this ArraySegment<byte> x, ArraySegment<byte> y)
    {
        if (x.Count == y.Count)
        {
            var xValue = (IEnumerable<byte>)x;
            var yValue = (IEnumerable<byte>)y;
            return xValue.SequenceEqual(yValue);
        }
        return false;
    }
#endif
}
```

If you think this modification is feasible, I will seriously modify and submit a pr.The related modification code is at https://github.com/xljiulang/MQTTnet/commit/913b27434e13563c2900cd1ac5744a5654a03a9d
