### ISSUE TITLE
Why are result models internal?

### ISSUE THREAD

**Issue by BEagle1984** [dotnet/MQTTnet#1637]
Is there a reason why in the last major release you decided to make it impossible to create e.g. a `MqttClientSubscribeResult` (all setters are internal)?
It just makes it harder to mock things on my side (https://github.com/BEagle1984/silverback).

**Comment by chkr1011** [comment]
They are internal to avoid having lots of constructors. In the past we got several bugs where the root cause was a wrong order in the parameters of the constructors. An object initializer is more clear what is being set. But on the other hand the state might be incomplete or wrong now because an object initializer does not guarantee that everything is set. So we are reverting to regular constructors.

But regardless of the way we choose I recommend that you create your own abstraction layer on top of this library with your own event arguments etc. which can be mocked in a way you need. If you want to move to another library you probably do not want to change all your code and tests.

**Comment by BEagle1984** [comment]
Thank you for the quick reply and sorry, I didn't see the public factory. 😄 

My library *is* the abstraction and I also provide an in-memory mock for the MQTT layer, to allow the users to unit test without an MQTT broker. Partially mocking the MqttClient I cover both needs: testing my library and allowing unit tests.
