### ISSUE TITLE
MqttApplicationMessage can no longer be deserialized

### ISSUE THREAD

**Issue by spudwebb** [dotnet/MQTTnet#1758]
### Describe the bug
MqttApplicationMessage can no longer be deserialized from json because the new `PayloadSegment` property is an `ArraySegment<byte>` which is a readonly struct.
The `Server_Retained_Message_Samples`  sample shows the problem and doesn't work in 4.2.1.781, but was working correctly in 4.1.4.563.

### Which component is your bug related to?
- Server

### To Reproduce
1. Using this version of MQTTnet '4.2.1.781'.
2. Run the Server_Retained_Message_Samples sample
3. Using a MQTT client send a retained message to the server
4. The sample app correctly serialize the message and save it to RetainedMessages.json
5. Exit and restart the Server_Retained_Message_Samples  sample
6. It tries to deserialize RetainedMessages.json but fails with the following exception:

```
System.NotSupportedException: The collection type 'System.ArraySegment`1[System.Byte]' is abstract, an interface, or is read only, and could not be instantiated and populated. Path: $[0].PayloadSegment | LineNumber: 0 | BytePositionInLine: 125.
```

### Expected behavior
No exception is thrown, and the json is correctly deserialized

**Comment by logicaloud** [comment]
I think the first question is whether it is a design goal to have a directly serializable `MqttApplicationMessage` object. That is probably one for @chkr1011 to answer. If yes, then it would mean to implement the different JSON serialization options available to the different target frameworks, or use a JSON library available to all of them, or limit support to some frameworks. So, either a dependency to NewtonSoft would need to be introduced or some conditional compiler directives would need to use `System.Text.Json` for newer frameworks and other serialization options for older ones.

Currently, directly serializing the `MqttApplicationMessage` would serialize the payload twice (once as the `Payload` member and once as the `PayloadSegement` member). Further, the `Payload` member is serialized as a Base64-encoded string and the `PayloadSegement` as a JSON array of numbers. So currently, even if deserialization of the `ArraySegement` worked, it would not be ideal.

Options as I see them are:

1. Add serialization support within the `MqttApplicationMessage` object with the implications as described above.

2. Update the `Server_Retained_Message_Samples` project to include an example how to serialize an `MqttApplicationMessage`, possibly limited to some framework (since it is an example only), or by using NewtonSoft as an external dependency. NewtonSoft is already used for some other tests and this would not introduce a dependency into the core `MQTTnet` project.

Thoughts?

**Comment by chkr1011** [comment]
I will update the sample soon. But the only working solution is to create a dedicated model used for serialization. This should only have a serializable payload like the previous byte array.

**Comment by spudwebb** [comment]
Thanks for the update. Works well.
