### ISSUE TITLE
Should I resubscribe topics manually after reconnection?

### ISSUE THREAD

**Issue by Tendx** [dotnet/MQTTnet#1813]
### Describe your question
Should I resubscribe topics manually after reconnection, or the broker will keep client subscribed topics?

### Which project is your question related to?
- Client

**Comment by chkr1011** [comment]
If you set the "Clean session" flag while connecting you have to resubscribe because the broker will discard all subscriptions. It is also required that the broker supports sessions and will also persist those sessions. Some are not doing this so that I recommend that you resubscribe after reconnection.
