### ISSUE TITLE
When the ProcessEvent throw an exception all subscribes will be lost

### ISSUE THREAD

**Issue by iswing** [dotnet/MQTTnet#1837]
I catch the exception at top scope, subscribes still lost,  but it no happend every time,  look like it happend in some special condition,how do i fix that?
```csharp
public class MqttEventBus
{
        _client = mqttFactory.CreateMqttClient();
        _mqttClientOptions = new MqttClientOptionsBuilder()
            .WithProtocolVersion(MqttProtocolVersion.V500)
            .WithCredentials("***", "***")
            .WithTcpServer("***.***.***", ***).Build();

        _ = Task.Run(
            async () =>
            {
                // User proper cancellation and no while(true).
                while (true)
                {
                    try
                    {
                        
                        // This code will also do the very first connect! So no call to _ConnectAsync_ is required in the first place.
                        if (await _client.TryPingAsync()) continue;
                        _logger.LogInformation("Try to connect the blocker");
                        await _client.ConnectAsync(_mqttClientOptions, CancellationToken.None);
                        _client.ApplicationMessageReceivedAsync += ProcessEventAsync;
                        _client.DisconnectedAsync += DisconnectedAsync;
                        SubscribeHandlers();
                        _logger.LogInformation("Connected");
                    }
                    catch (Exception e)
                    {
                        _logger.LogException(e);
                    }
                    finally
                    {
                        // Check the connection state every 5 seconds and perform a reconnect if required.
                        await Task.Delay(TimeSpan.FromSeconds(5));
                    }
                }
            });

}

    private Task DisconnectedAsync(MqttClientDisconnectedEventArgs arg)
    {
        _logger.LogInformation("DisconnectedAsync");
        return Task.CompletedTask;
    }


 private async Task ProcessEventAsync(
        MqttApplicationMessageReceivedEventArgs mqttApplicationMessageReceivedEventArgs)
    {
  
     
            try
            {
      
                await TriggerHandlersAsync();
            }
            catch (Exception e)
            {
                mqttApplicationMessageReceivedEventArgs.ProcessingFailed = true;
                _logger.LogError(e, message: "ProcessEventError");
            }
        }
    }

```
### logs

![image](https://github.com/dotnet/MQTTnet/assets/1507547/30f5a2be-1a92-44fd-90ca-29a8d7d1e880)

**Comment by iswing** [comment]
The problem still in my product environment，I try to publish rpc ping/pong message to other computer for monitor this problem on a same client instance.

Then it can receive well，I also used third part tools(mqttx) to publish a new message，it receive well too，i think the exception only stopped real device messages，so i am confused about this.

Any one have an idea for help， thanks!

**Comment by rlkollman** [comment]
If it works when you publish a message with mqttx, then my best guess is the message being sent from the actual device, sometimes has an unexpected character or value in the payload, and your TriggerHandlersAsync() isn't able to handle that.  I do quite a bit with GPS Devices and I've run into issues where, perhaps I expected the course/direction to be an integer because that was what my test packet had, but from time to time, the actual device was sending a decimal/double, or null, and that threw exceptions - perhaps this is something similar.

You should log the contents of the received message payload when there is an exception to see if there is something unusual about the payload contents.  As well, you should create additional try/catch methods within TriggerHandlersAsync() and nested methods to narrow down where the exception is being thrown.

**Comment by iswing** [comment]
Finally，I fix this issue via Task.Run，Process event code execute in the other thread，I have not find the reason why we can't thow exception in First thead.
