### ISSUE TITLE
MqttServer messages send get lost while client is subscribing

### ISSUE THREAD

**Issue by DerGary** [dotnet/MQTTnet#1970]
### Describe the bug
When a message is send from the MqttServer class through `InjectApplicationMessage` while in the `InterceptingSubscriptionAsync` event handler, the message gets lost. In other words, messages send while the client is subscribing are getting lost.

### Which component is your bug related to?
- Server

### To Reproduce
I created a XUnit test project with 2 Unit Tests one that will fail due to the bug, and another one that uses a workaround (small delay before sending a message) which will succeed. The Repro is available at: https://github.com/DerGary/mqttnet-subscribe-bug-repro/tree/main

### Expected behavior
Messages send while in the `InterceptingSubscriptionAsync` do not get lost, as it is the only way to know when a client subscribed to a topic.

### Code example
https://github.com/DerGary/mqttnet-subscribe-bug-repro/tree/main

Test Output:
```
Starting test run
[Failed] repro.test.UnitTest1.Test_ReceiveMessageWhileSubscribing_WillFail
    Message:
        Assert.Fail(): System.Threading.Tasks.TaskCanceledException: A task was canceled.
           at repro.test.UnitTest1.ActAndAssert() in /home/gary/git/mqtt-bug-repro/repro.test/UnitTest1.cs:line 84
    Stack Trace:
           at repro.test.UnitTest1.ActAndAssert() in /home/gary/git/mqtt-bug-repro/repro.test/UnitTest1.cs:line 90
           at repro.test.UnitTest1.Test_ReceiveMessageWhileSubscribing_WillFail() in /home/gary/git/mqtt-bug-repro/repro.test/UnitTest1.cs:line 59
        --- End of stack trace from previous location ---

[Passed] repro.test.UnitTest1.Test_ReceiveMessageWhileSubscribing_Workaround_WillSucceed
==== Summary ====
Failed!  - Failed:    1, Passed:    1, Skipped:    0, Total:    2, Duration: 21s
```

**Comment by chkr1011** [comment]
I don't think that this is a bug. In my opinion it should never work by design.

The reason is that you are intercepting the subscription which means your code is executed **before** the subscription is fully processed. This is required to allow for denying a subscription or cancel it completely. So publishing a message in the interception event cannot work because the subscription is not stored internally. That also explains why it works with a small delay.

You may try to use _ClientSubscribedTopicAsync_ event instead. This event is fired when the subscription is fully processed.

**Comment by DerGary** [comment]
Oh my bad I have not found the `ClientSubscribedTopicAsync `until now. But that explains a lot. Thank you.
