### ISSUE TITLE
Implicitly set the version number in MqttClientOptionsBuilder

### ISSUE THREAD

**Issue by jimsch** [dotnet/MQTTnet#656]
It would be nice if the version number is implicitly set when doing something like calling WithAuthentication.  This is only supported in V5+ so keeping the version number at 3.1.1 does not make a lot of sense.

Alternatively would be a check that the options set match the version number and fail if they dont.

**Comment by chkr1011** [comment]
Hi,
I agree that some validations are missing in the options builder or the client directly. But setting the protocol version implicitly is questionable. Because if you set some feature by accident you just will get a "protocol version not supported" exception and no one realizes why the version is sometimes x and sometimes y. This would require some knowledge of internals of that library which I want to avoid. But I agree that general version scoped validations make sense.

Best regards
Christian
