### ISSUE TITLE
Is it possible to set ClientId from server?

### ISSUE THREAD

**Issue by SimonOrdo** [dotnet/MQTTnet#660]
If I'm sending a message from inside of the server via `MQTTServer.PublishAsync` , is it possible to set a client id somehow?  In other words, I'd like to impersonate a particular client  from within the server.

TIA!

**Comment by SeppPenner** [comment]
I don't believe that this is possible. Neither do I believe that this is possible in the MQTT protocol at all...

**Comment by SeppPenner** [comment]
From https://www.hivemq.com/blog/mqtt-essentials-part-3-client-broker-connection-establishment/:

> The client identifier (ClientId) identifies each MQTT client that connects to an MQTT broker. The broker uses the ClientID to identify the client and the current state of the client.Therefore, this ID should be unique per client and broker. In MQTT 3.1.1 (the current standard), you can send an empty ClientId, if you don’t need a state to be held by the broker. The empty ClientID results in a connection without any state. In this case, the clean session flag must be set to true or the broker will reject the connection.

What you're trying to do is not desired in MQTT and thus not possible. @chkr1011: I would close this issue if I were you.

**Comment by chkr1011** [comment]
That is indeed not possible in general. But from another point of view I see a small Use Case so that a user can send something in behalf of another client. But this will require some small rework of the server API.

I am also not sure if the part from the spec is supported which allows sending an empty string as the client ID. I will verify if this is implemented properly.

**Comment by SeppPenner** [comment]
> But from another point of view I see a small Use Case so that a user can send something in behalf of another client

Don't you think that this is kind of a security issue then?

**Comment by chkr1011** [comment]
I am just referring to the server. There you can already intercept entire messages and publish custom messages. So setting the ClientId (instead of using the servers default one) should be fine in my opinion. 

But you are right with security concerns. But the users is responsible for this if he really want to use a custom client ID for some (strange) Use Case. I would rather not do that but I accept that this might a Use Case for someone else. What do you think?

**Comment by SeppPenner** [comment]
I agree on this. There might be a use case for this.

**Comment by nicholasdgoodman** [comment]
Bumping an old issue:

Similarly, I would likewise like to be able to set a ClientId from the server / broker; but during connect rather than publish.

I am looking for the ability to override the supplied ClientId from within the `OnNewConnection` handler (aka `UseClientConnectedHander`) and be able to substitute or prefix the value with the `Endpoint` or some other metadata.

My reason is that I have dozens of device clients which all run the same software and have no way of uniquely identifying themselves other than their hard-coded (statically assigned) IP addresses, which is not readable from within the program logic.

**Comment by chkr1011** [comment]
When using MQTTv5 you can leave the client id empty and the server will generate/choose one and returns it in the PUBACK packet. This is also supported in this library.

**Comment by chkr1011** [comment]
I assume the initial question is answered.
