### ISSUE TITLE
Improve performance of subscription management in server

### ISSUE THREAD

**Issue by JanEggers** [dotnet/MQTTnet#827]
### Describe the feature request
https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientSubscriptionsManager.cs

MqttClientSubscriptionsManager does a linear search over all subscriptions to see if one matches the publish packet that needs to be distributed.

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
I created a prototype based on a dictionary approach that splits the topic and creates an index by level. I added special handling for wildcards. The protoype uses Span api to avoid allocations while doing the search so I have to adjust the algorithm a little but still. I think this should be a good improvement on the overall performance. 

### Benchmarks
the number indicates the number of subscriptions the algorithm has to go through:

|       Method |      Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |----------:|---------:|---------:|-------:|------:|------:|----------:|
| LinearSearch 10 | 130.75 ns | 0.855 ns | 0.800 ns | 0.0076 |     - |     - |      32 B |
|  IndexSearch 10 |  93.06 ns | 0.698 ns | 0.619 ns | 0.0153 |     - |     - |      64 B |
| LinearSearch 100 | 954.1 ns | 12.05 ns | 11.27 ns | 0.0076 |     - |     - |      32 B |
|  IndexSearch 100 | 138.3 ns |  0.91 ns |  0.85 ns | 0.0229 |     - |     - |      96 B |
| LinearSearch 1000 | 7,381.3 ns | 31.55 ns | 24.64 ns | 0.0076 |     - |     - |      32 B |
|  IndexSearch 1000 |   137.7 ns |  0.90 ns |  0.84 ns | 0.0229 |     - |     - |      96 B |

regarding a pull request: should I replace the existing MqttClientSubscriptionsManager or should I make this part pluggable and create a separate implementation? also I would apprecheate any thoughts about edge cases I might have missed.

**Comment by JanEggers** [comment]
@chkr1011 Hi christian I ported the changes to the current dev branch but im not able to run the unittests because clients leak from one test to the next. 

Is this also broken for you / do you have some advice?

**Comment by SeppPenner** [comment]
Related to PR https://github.com/chkr1011/MQTTnet/pull/874.

**Comment by chkr1011** [comment]
@JanEggers I this still relevant? I changed the CI to use VS2019 now and it builds properly. But some tests are still failing. I assume due to race conditions...

I recommend to create a proper interface and "inject" a different implementation depending on the platform. I assume Span etc. will not work for 4.5 and UWP right?

**Comment by JanEggers** [comment]
the implementation is not platform dependent, I have to check if the tests are reliable now

**Comment by chkr1011** [comment]
OK if it works on all platforms then we don't need separate implementations I guess.
I also have a look at the UnitTests. The problem is that they are running twice because you added net461 and netcoreapp3.1 to the target platform. I am not sure if we should remove one of them or how to deal with that. But you can also have a look if you are able to fix some of the tests.

**Comment by chkr1011** [comment]
I assume this ticket is obsolete.
